      SUBROUTINE DELK0 ( EV2K   , ESTR   , VALSYM , VALASY ,
     1                   SMAT   , HMAT   , NOFSET , NDIMST ,
     1                   JP1    , IRODIM , IEO    , ITAU   ,
     1                   INTSYM , INTASY , ISTOFF ,
     4                   NOPERS       )
      IMPLICIT REAL*8 (A-H,O-Z)
C
      REAL*8 M1,M2,M3,M,U1,U3,U13,V,RHO,EPS,
     1      CR,SR,CSE,SNE,
     2      CRE,SRE,CORO,EPSP,EPSPP,EPSPPP
C
      REAL*8 AMASS(3,10)
C
      REAL*8 RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1       AA1,AA3,
     2       F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3       F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4       F13,F1A13,F2A13,F3A13,
     5       F111,F1A111,F2A111,F333,F1A333,F2A333,
     6       F113,F1A113,F2A113,F133,F1A133,F2A133,
     7       F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8       F1333,FA1333,F1133,FA1133,
     8       RE12 , RE32 , RHOREF , VMIN
C
      REAL*8 ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1      PREC
C
      REAL*8 THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1      THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2      VELLGT , PLANCK , AVOGNO , DEGRAD , RADDEG ,
     3      PI
C
      REAL*8   B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      REAL*8   CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
      INTEGER NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 , NFIL6 ,
     5       NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6       NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7       NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6       ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7       IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8       NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER,
     9       ISOMAX , NATTS  , V0TYPE , IVAR(55) , PARMAX ,
     1       NUMPAR , PRTINT
C
      INTEGER V1 ,V2, V3 , V2MXP1, V2P1,
     1       NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2       NSEPP2 , NSEQP1 , MBASIS ,
     3       MDIM , NFSYM0, NFASY0, NFSYMJ, NFASYJ,
     4       KSTYPA(2) , LSTYPA(2) , JMAX , V2MAX , JMAXP1
C
      INTEGER IQUANT(5,10)
C
      LOGICAL SYMM
C
      REAL*8 RMK(2),AAS(2)
      INTEGER NOBAS,MBASP1,LENIW
      INTEGER LENINT,IOSC1,IOSC3,I,J,IR,JL
      REAL*8 G,GC1,GC3,GC1113,GC3133,GC1133,GC3113
      REAL*8  EV2K(V2MXP1,JMAXP1),ESTR(NOBAS),
     1       SMAT(NOBAS,NOBAS,NOPERS),VALSYM(INTSYM),VALASY(INTASY),
     1       HMAT(IRODIM,IRODIM)
      REAL*8  CONCOR,CONFC1,CONG11,CONG33,CONG13,CORHOE
      COMMON /ISOTOP/ IQUANT,AMASS
C
      COMMON /BOOKK/ NZERSY , NZERAS , NONESY , NONEAS , NTWOSY ,
     1               NTWOAS , KZERSY , KZERAS , KONESY , KONEAS ,
     2               KTWOSY , KTWOAS
C
      COMMON /VALUES/ RHO,EPS,EPSP,EPSPP,EPSPPP,
     1               CR,SR,CSE,SNE,CRE,SRE,CORO
C
      COMMON /MOLCUL/ RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1               AA1,AA3,
     2               F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3               F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4               F13,F1A13,F2A13,F3A13,
     5               F111,F1A111,F2A111,F333,F1A333,F2A333,
     6               F113,F1A113,F2A113,F133,F1A133,F2A133,
     7               F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8               F1333,FA1333,F1133,FA1133,
     8               RE12 , RE32 , M1 , M2 , M3 , M ,
     9               U1 , U3 , U13 , V ,
     1               SYMM
C
      COMMON /INTEG/  ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1               RHOREF , VMIN , V0TYPE ,
     1               NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2               NSEPP2 , NSEQP1 , KSTYPA , LSTYPA
C
      COMMON /DIMEN/  MBASIS ,  V2MAX  , V2MXP1 ,
     1               JMAX   , JMAXP1 , MDIM   , NFSYM0 , NFASY0 ,
     2               NFSYMJ , NFASYJ
C
      COMMON /LSFIT/  PARMAX , NUMPAR , ISOMAX , IVAR
C
      COMMON /SYS/    THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1                     THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2                     VELLGT , PLANCK , AVOGNO , PI , PREC ,
     4                     NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 ,
     5                     NFIL6 , NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6                     NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7                     NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6                     ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7                     IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8                     NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER ,
     9                       NATTS , PRTINT
C
      COMMON/BCOEFF/
     1      B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      COMMON/CRCOEF/
     1      CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
C
      COMMON/MORSE/RMK,AAS
      COMMON/MODIM/NOBAS,MBASP1,LENIW
C
      CONCOR=PLANCK*AVOGNO*1.0D+16/(1.6D+01*PI*PI*VELLGT)
      CONRR=2.0D+00*CONCOR
      CONXX=CONCOR
      CONZZ=2.0D+00*CONXX
      CONFC1=2.0D+00*CONCOR
      CONG13=-CONFC1/M2
      J=JP1-1
      CORHOE=COS(RHOE)
      REWIND NFIL9
      DO 5000 III=1,KZERSY
      IOFFSY=(III-1)*NZERSY
5000  READ (NFIL9 ) (VALSYM(IOFFSY+L), L=1,NZERSY)
      KBDSYM=0
      IF (.NOT. SYMM) THEN
      REWIND NFIL10
      DO 5010 III=1,KZERAS
      IOFFAS=(III-1)*NZERAS
5010  READ (NFIL10) (VALASY(IOFFAS+L), L=1,NZERAS)
      KBDASY=0
      ENDIF
C
      XJJP1=FLOAT(J*JP1)
      IF (MOD(J+ITAU,2) .NE. 0) XJJP1=-XJJP1
C
      DO 940 KP1=1,JP1
      XJK=FLOAT(J*JP1-(KP1-1)*(KP1-1))
C
      DO 920 INDEX1=1,V2MXP1
      DO 900 INDEX2=1,V2MXP1
C
      KBDSYM=KBDSYM+1
      IOFFSY=(KBDSYM-1)*NZERSY
      IF (.NOT.SYMM) THEN
          KBDASY=KBDASY+1
          IOFFAS=(KBDASY-1)*NZERAS
      ENDIF
      IF (MOD(KP1,2) .EQ. IEO) GOTO 900
      IF (MOD(J+ITAU,2) .NE. 0  .AND. KP1 .EQ. 1)  GOTO 900
C
      KNDEX=0
C
      IF (MOD(KP1,2) .NE. 0) THEN
            INDK=(KP1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK=INDK-1
      ELSE
            INDK=(KP1-2)/2
      ENDIF
      IROWOF=NOFSET+INDK*V2MXP1*NDIMST+(INDEX1-1)*NDIMST
      ICOLOF=NOFSET+INDK*V2MXP1*NDIMST+(INDEX2-1)*NDIMST
C
C  0. ZERO ORDER ENERGIES ADDED IN DIAGONAL ELEMENTS
C
      IF (INDEX1 .EQ. INDEX2) THEN
      DO  50 IR=1,NDIMST
50    HMAT(IROWOF+IR,IROWOF+IR)=HMAT(IROWOF+IR,IROWOF+IR)
     1       + EV2K(INDEX1,KP1)+ESTR(ISTOFF+IR)
      ENDIF
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C     CONTRIBUTIONS FROM:   A. MUXX0+MUYY0
C                           B. CORIOLIS COMMUTATOR TERMS
C                           C. G MATRIX COMMUTATOR TERMS
C                           D. PSEUDOPOTENTIAL TERM
C
      G =  VALSYM(IOFFSY+10)
     1 + CONXX*(VALSYM(IOFFSY+32)+VALSYM(IOFFSY+41))*XJK
      GCOR1= CONCOR*AA1*VALSYM(IOFFSY+23)
      IF (SYMM) THEN
            GCOR3=GCOR1
      ELSE
            GCOR3= CONCOR*AA3*VALASY(IOFFAS+16)
      ENDIF
      GGMAT=-CONG13*AA1*AA3*VALSYM(IOFFSY+22)/2.0D+00
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+32)-
     2                VALSYM(IOFFSY+41))*XJJP1
      DO 100 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+IR)=HMAT(ICOLOF+IR,IROWOF+IR)
     1                       +GCOR1+GCOR3
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G +GCOR1+GCOR3+GGMAT
C
C  2. TERMS CONTAINING Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                           E. CORIOLIS COMMUTATOR TERMS
C                           F. G MATRIX COMMUTATOR TERMS
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+2)
     1  + VALSYM(IOFFSY+11)
     1  + CONXX*(VALSYM(IOFFSY+33)+VALSYM(IOFFSY+42))*XJK
     2  + CONZZ*VALSYM(IOFFSY+51)
      GCOR1=-CONCOR*AA1*VALSYM(IOFFSY+23)
     1     + 2.0D+00*CONCOR*AA1*VALSYM(IOFFSY+25)
      IF (SYMM) THEN
            GCOR3= CONCOR*AA1*VALSYM(IOFFSY+27)
      ELSE
            GCOR3= CONCOR*AA3*VALASY(IOFFAS+19)
      ENDIF
      GGMAT=CONG13*AA1*AA3*VALSYM(IOFFSY+22)/2.0D+00
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+33)-
     2                     VALSYM(IOFFSY+42))*XJJP1
      DO 120 JL=1,NDIMST
      DO 120 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1        +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1   +(GGMAT+G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 3. TERMS CONTAINING Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(IOFFAS+1)
     1                  + VALASY(IOFFAS+7)
     2                  + CONXX*(VALASY(IOFFAS+24)
     3                  + VALASY(IOFFAS+30))*XJK
     3                  + CONZZ*VALASY(IOFFAS+36)
                      GCOR1= CONCOR*AA1*VALSYM(IOFFSY+27)
                      GCOR3=-CONCOR*AA3*VALASY(IOFFAS+16)
     1                     +2.0D+00*CONCOR*AA3*VALASY(IOFFAS+18)
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(IOFFAS+24)-
     2                             VALASY(IOFFAS+30))*XJJP1
      DO 140 JL=1,NDIMST
      DO 140 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1          +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1     +(GGMAT+G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C  4. TERMS CONTAINING Y1*Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                           E. CORIOLIS COMMUTATOR TERMS
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+3)
     1  + VALSYM(IOFFSY+12)
     1  + CONXX*(VALSYM(IOFFSY+34)+VALSYM(IOFFSY+43))*XJK
     2  + CONZZ*VALSYM(IOFFSY+52)
      GCOR1=-2.0D+00*CONCOR*AA1*VALSYM(IOFFSY+25)
     1     +3.0D+00*CONCOR*AA1*VALSYM(IOFFSY+28)
      IF (SYMM) THEN
            GCOR3= CONCOR*AA1*VALSYM(IOFFSY+31)
      ELSE
            GCOR3= CONCOR*AA3*VALASY(IOFFAS+22)
      ENDIF
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+34)
     2                            -VALSYM(IOFFSY+43))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F11
      DO 160 JL=1,NDIMST
      DO 160 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1         +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1        +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 5. TERMS CONTAINING Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(IOFFAS+2)
     1                  + VALASY(IOFFAS+8)
     2                  + CONXX*(VALASY(IOFFAS+25)
     3                   +VALASY(IOFFAS+31))*XJK
     3                  + CONZZ*VALASY(IOFFAS+37)
                    GCOR1= CONCOR*AA1*VALSYM(IOFFSY+31)
                    GCOR3=-2.0D+00*CONCOR*AA3*VALASY(IOFFAS+18)
     1                   +3.0D+00*CONCOR*AA3*VALASY(IOFFAS+21)
      IF (INDEX1 .EQ. INDEX2) G = G - F33
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(IOFFAS+25)
     2                   -VALASY(IOFFAS+31))*XJJP1
      DO 180 JL=1,NDIMST
      DO 180 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1      +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 6. TERMS CONTAINING Y1*Y3
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+4)
     1  + VALSYM(IOFFSY+13)
     2  + CONXX*(VALSYM(IOFFSY+35)+VALSYM(IOFFSY+44))*XJK
     3  + CONZZ*VALSYM(IOFFSY+53)
      GCOR1=-CONCOR*AA1*VALSYM(IOFFSY+27)
     1     +2.0D+00*CONCOR*AA1*VALSYM(IOFFSY+30)
      IF (SYMM) THEN
            GCOR3=GCOR1
      ELSE
            GCOR3=-CONCOR*AA3*VALASY(IOFFAS+19)
     1           +2.0D+00*CONCOR*AA3*VALASY(IOFFAS+23)
      ENDIF
      GGMAT=-CONG13*AA1*AA3*VALSYM(IOFFSY+22)/2.0D+00
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+35)
     2                     -VALSYM(IOFFSY+44))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F13
      DO 200 JL=1,NDIMST
      DO 200 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1       +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1    +(GGMAT+G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                           E. CORIOLIS COMMUTATOR TERMS
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+5)
     1  + VALSYM(IOFFSY+14)
     1  + CONXX*(VALSYM(IOFFSY+36)+VALSYM(IOFFSY+45))*XJK
     2  + CONZZ*VALSYM(IOFFSY+54)
      GCOR1=-3.0D+00*CONCOR*AA1*VALSYM(IOFFSY+28)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+36)
     2                       -VALSYM(IOFFSY+45))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F111
      DO 220 JL=1,NDIMST
      DO 220 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +GCOR1*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GCOR1)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(IOFFAS+3)
     1                  + VALASY(IOFFAS+9)
     2                  + CONXX*(VALASY(IOFFAS+26)
     3                  + VALASY(IOFFAS+32))*XJK
     3                  + CONZZ*VALASY(IOFFAS+38)
                    GCOR1=-3.0D+00*CONCOR*AA3*VALASY(IOFFAS+21)
      IF (INDEX1 .EQ. INDEX2) G = G - F333
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(IOFFAS+26)
     2                     -VALASY(IOFFAS+32))*XJJP1
      DO 240 JL=1,NDIMST
      DO 240 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       +GCOR1*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GCOR1)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C                            E. CORIOLIS COMMUTATOR TERMS
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+6)
     1  + VALSYM(IOFFSY+15)
     1  + CONXX*(VALSYM(IOFFSY+37)+VALSYM(IOFFSY+46))*XJK
     2  + CONZZ*VALSYM(IOFFSY+55)
      GCOR1=-2.0D+00*CONCOR*AA1*VALSYM(IOFFSY+30)
      IF (SYMM) THEN
            GCOR3=-CONCOR*AA1*VALSYM(IOFFSY+31)
      ELSE
            GCOR3=-CONCOR*AA3*VALASY(IOFFAS+22)
      ENDIF
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+37)
     2                            -VALSYM(IOFFSY+46))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F113
      DO 260 JL=1,NDIMST
      DO 260 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1         +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1        +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) THEN
                      G = CONRR*VALASY(IOFFAS+4)
     1                  + VALASY(IOFFAS+10)
     2                  + CONXX*(VALASY(IOFFAS+27)
     3                          +VALASY(IOFFAS+33))*XJK
     3                  + CONZZ*VALASY(IOFFAS+39)
                    GCOR3=-2.0D+00*CONCOR*AA3*VALASY(IOFFAS+23)
                    GCOR1=-CONCOR*AA1*VALSYM(IOFFSY+30)
      IF (INDEX1 .EQ. INDEX2) G = G - F133
      ENDIF
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(IOFFAS+27)
     3                            -VALASY(IOFFAS+33))*XJJP1
      DO 280 JL=1,NDIMST
      DO 280 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1        +(GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1     +(G+GCOR1+GCOR3)*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+7)
     1  + VALSYM(IOFFSY+16)
     1  + CONXX*(VALSYM(IOFFSY+38)+VALSYM(IOFFSY+47))*XJK
     2  + CONZZ*VALSYM(IOFFSY+56)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+38)
     3                            -VALSYM(IOFFSY+47))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F1111
      DO 300 JL=1,NDIMST
      DO 300 IR=1,NDIMST
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONRR*VALASY(IOFFAS+5)
     1                  + VALASY(IOFFAS+11)
     2                  + CONXX*(VALASY(IOFFAS+28)
     3                  + VALASY(IOFFAS+34))*XJK
      IF (INDEX1 .EQ. INDEX2 .AND. .NOT. SYMM) G = G - F3333
     3                  + CONZZ*VALASY(IOFFAS+40)
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(IOFFAS+28)
     2                            -VALASY(IOFFAS+34))*XJJP1
      DO 320 JL=1,NDIMST
      DO 320 IR=1,NDIMST
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C     CONTRIBUTIONS FROM:   A. MU(RHO,RHO)0
C                           B. THE POTENTIAL ENERGY FUNCTION
C                           C. MUXX0+MUYY0
C                           D. MUZZ0
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+8)
     1  + VALSYM(IOFFSY+17)
     1  + CONXX*(VALSYM(IOFFSY+39)+VALSYM(IOFFSY+48))*XJK
     2  + CONZZ*VALSYM(IOFFSY+57)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+39)
     2                            -VALSYM(IOFFSY+48))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F1113
      DO 340 JL=1,NDIMST
      DO 340 IR=1,NDIMST
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONRR*VALASY(IOFFAS+6)
     1                  + VALASY(IOFFAS+12)
     2                  + CONXX*(VALASY(IOFFAS+29)
     3                          +VALASY(IOFFAS+35))*XJK
     3                  + CONZZ*VALASY(IOFFAS+41)
      IF (KP1 .EQ. 2 .AND. .NOT. SYMM)
     1      G = G + 0.5D+00*CONXX*(VALASY(IOFFAS+29)
     2                            -VALASY(IOFFAS+35))*XJJP1
      IF (INDEX1 .EQ. INDEX2 .AND. .NOT. SYMM) G = G - F1333
      DO 360 JL=1,NDIMST
      DO 360 IR=1,NDIMST
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      G = CONRR*VALSYM(IOFFSY+9)
     1  + VALSYM(IOFFSY+18)
     2  + CONXX*(VALSYM(IOFFSY+40)+VALSYM(IOFFSY+49))*XJK
     3  + CONZZ*VALSYM(IOFFSY+58)
      IF (KP1 .EQ. 2)
     1      G = G + 0.5D+00*CONXX*(VALSYM(IOFFSY+40)
     2                            -VALSYM(IOFFSY+49))*XJJP1
      IF (INDEX1 .EQ. INDEX2) G = G - F1133
      DO 380 JL=1,NDIMST
      DO 380 IR=1,NDIMST
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 22. TERMS CONTAINING Y1*P1+P1*Y1
C
      KNDEX=KNDEX+1
      G = CONCOR*VALSYM(IOFFSY+23)
      DO 540 JL=1,NDIMST
      DO 540 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
540   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 23. TERMS CONTAINING Y3*P3+P3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONCOR*VALASY(IOFFAS+16)
      DO 560 JL=1,NDIMST
      DO 560 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
560   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 24. TERMS CONTAINING Y3*P1
C
      KNDEX=KNDEX+1
      G = 2.0D+00*CONCOR*VALSYM(IOFFSY+24)
      DO 580 JL=1,NDIMST
      DO 580 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
580   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 25. TERMS CONTAINING Y1*P3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*VALASY(IOFFAS+15)
      DO 600 JL=1,NDIMST
      DO 600 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
600   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 26. TERMS CONTAINING Y1*Y1*P1+P1*Y1*Y1
C
      KNDEX=KNDEX+1
      G = CONCOR*VALSYM(IOFFSY+25)
      DO 620 JL=1,NDIMST
      DO 620 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
620   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 27. TERMS CONTAINING Y3*Y3*P3+P3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONCOR*VALASY(IOFFAS+18)
      DO 640 JL=1,NDIMST
      DO 640 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
640   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 28. TERMS CONTAINING P1*Y3*Y3
C
      KNDEX=KNDEX+1
      G = 2.0D+00*CONCOR*VALSYM(IOFFSY+26)
      DO 660 JL=1,NDIMST
      DO 660 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
660   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 29. TERMS CONTAINING P3*Y1*Y1
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*VALASY(IOFFAS+17)
      DO 680 JL=1,NDIMST
      DO 680 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
680   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 30. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3
C
      KNDEX=KNDEX+1
      G = CONCOR*VALSYM(IOFFSY+27)
      DO 700 JL=1,NDIMST
      DO 700 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
700   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 31. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONCOR*VALASY(IOFFAS+19)
      DO 720 JL=1,NDIMST
      DO 720 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
720   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 32. TERMS CONTAINING Y1*Y1*Y1*P1+P1*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      G = CONCOR*VALSYM(IOFFSY+28)
      DO 740 JL=1,NDIMST
      DO 740 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
740   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 33. TERMS CONTAINING Y3*Y3*Y3*P3+P3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONCOR*VALASY(IOFFAS+21)
      DO 760 JL=1,NDIMST
      DO 760 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
760   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 34. TERMS CONTAINING P1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G = 2.0D+00*CONCOR*VALSYM(IOFFSY+29)
      DO 780 JL=1,NDIMST
      DO 780 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
780   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 35. TERMS CONTAINING P3*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*VALASY(IOFFAS+20)
      DO 800 JL=1,NDIMST
      DO 800 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
800   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 36. TERMS CONTAINING (Y1*Y1*P1+P1*Y1*Y1)*Y3
C
      KNDEX=KNDEX+1
      G = CONCOR*VALSYM(IOFFSY+30)
      DO 820 JL=1,NDIMST
      DO 820 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
820   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 37. TERMS CONTAINING (Y3*Y3*P3+P3*Y3*Y3)*Y1
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONCOR*VALASY(IOFFAS+23)
      DO 840 JL=1,NDIMST
      DO 840 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
840   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 38. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3*Y3
C
      KNDEX=KNDEX+1
      G = CONCOR*VALSYM(IOFFSY+31)
      DO 860 JL=1,NDIMST
      DO 860 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
860   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 39. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1*Y1
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONCOR*VALASY(IOFFAS+22)
      DO 880 JL=1,NDIMST
      DO 880 IR=1,NDIMST
      HMAT(ICOLOF+IR,IROWOF+JL)=HMAT(ICOLOF+IR,IROWOF+JL)
     1                       -G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
880   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 16. TERMS CONTAINING P1*P3
C
      KNDEX=KNDEX+1
      G = 2.0D+00*CONG13*VALSYM(IOFFSY+19)
      IF (INDEX1 .EQ. INDEX2) G = G + 2.0D+00*CONG13*CORHOE
      DO 400 JL=1,NDIMST
      DO 400 IR=1,NDIMST
400   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 17. TERMS CONTAINING Y1*P1*P3
C
      KNDEX=KNDEX+1
      G = CONG13*VALSYM(IOFFSY+20)
      DO 420 JL=1,NDIMST
      DO 420 IR=1,NDIMST
420   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 18. TERMS CONTAINING Y3*P1*P3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM) G = CONG13*VALASY(IOFFAS+13)
      DO 440 JL=1,NDIMST
      DO 440 IR=1,NDIMST
440   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 19. TERMS CONTAINING Y1*Y1*P1*P3
C
      KNDEX=KNDEX+1
      G = CONG13*VALSYM(IOFFSY+21)
      DO 460 JL=1,NDIMST
      DO 460 IR=1,NDIMST
460   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 20. TERMS CONTAINING Y3*Y3*P1*P3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM)  G = CONG13*VALASY(IOFFAS+14)
      DO 480 JL=1,NDIMST
      DO 480 IR=1,NDIMST
480   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
C
C 21. TERMS CONTAINING Y1*Y3*P1*P3
C
      KNDEX=KNDEX+1
      G = CONG13*VALSYM(IOFFSY+22)/2.0D+00
      DO 500 JL=1,NDIMST
      DO 500 IR=1,NDIMST
500   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,ISTOFF+JL,KNDEX)
900   CONTINUE
920   CONTINUE
940   CONTINUE
      RETURN
      END
C
C
      SUBROUTINE DELK1 ( VALSYM , VALASY , SMAT   , HMAT   ,
     1                   NOFSRO , NOFSCO , NDIMRO , NDIMCO ,
     1                   JP1    , IRODIM , IEO    , ITAU   ,
     1                   INTSYM , INTASY , ISTOFF , JSTOFF ,
     4                   NOPERS       )
      IMPLICIT REAL*8 (A-H,O-Z)
C
      REAL*8 M1,M2,M3,M,U1,U3,U13,V,RHO,EPS,
     1      CR,SR,CSE,SNE,
     2      CRE,SRE,CORO,EPSP,EPSPP,EPSPPP
C
      REAL*8 AMASS(3,10)
C
      REAL*8 RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1       AA1,AA3,
     2       F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3       F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4       F13,F1A13,F2A13,F3A13,
     5       F111,F1A111,F2A111,F333,F1A333,F2A333,
     6       F113,F1A113,F2A113,F133,F1A133,F2A133,
     7       F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8       F1333,FA1333,F1133,FA1133,
     8       RE12 , RE32 , RHOREF , VMIN
C
      REAL*8 ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1      PREC
C
      REAL*8 THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1      THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2      VELLGT , PLANCK , AVOGNO , DEGRAD , RADDEG ,
     3      PI
C
      REAL*8   B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      REAL*8   CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
      INTEGER NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 , NFIL6 ,
     5       NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6       NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7       NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6       ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7       IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8       NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER,
     9       ISOMAX , NATTS  , V0TYPE , IVAR(55) , PARMAX ,
     1       NUMPAR , PRTINT
C
      INTEGER V1 ,V2, V3 , V2MXP1, V2P1,
     1       NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2       NSEPP2 , NSEQP1 , MBASIS ,
     3       MDIM , NFSYM0, NFASY0, NFSYMJ, NFASYJ,
     4       KSTYPA(2) , LSTYPA(2) , JMAX , V2MAX , JMAXP1
C
      INTEGER IQUANT(5,10)
C
      LOGICAL SYMM
C
      REAL*8 RMK(2),AAS(2)
      INTEGER NOBAS,MBASP1,LENIW
      INTEGER LENINT,IOSC1,IOSC3,I,J,IR,JL
      REAL*8 G,GC1,GC3,GC1113,GC3133,GC1133,GC3113
      REAL*8  SMAT(NOBAS,NOBAS,NOPERS),VALSYM(INTSYM),VALASY(INTASY),
     1       HMAT(IRODIM,IRODIM)
      REAL*8  CONCOR,CONFC1,CONG11,CONG33,CONG13,CORHOE
      COMMON /ISOTOP/ IQUANT,AMASS
C
      COMMON /BOOKK/ NZERSY , NZERAS , NONESY , NONEAS , NTWOSY ,
     1               NTWOAS , KZERSY , KZERAS , KONESY , KONEAS ,
     2               KTWOSY , KTWOAS
C
      COMMON /VALUES/ RHO,EPS,EPSP,EPSPP,EPSPPP,
     1               CR,SR,CSE,SNE,CRE,SRE,CORO
C
      COMMON /MOLCUL/ RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1               AA1,AA3,
     2               F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3               F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4               F13,F1A13,F2A13,F3A13,
     5               F111,F1A111,F2A111,F333,F1A333,F2A333,
     6               F113,F1A113,F2A113,F133,F1A133,F2A133,
     7               F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8               F1333,FA1333,F1133,FA1133,
     8               RE12 , RE32 , M1 , M2 , M3 , M ,
     9               U1 , U3 , U13 , V ,
     1               SYMM
C
      COMMON /INTEG/  ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1               RHOREF , VMIN , V0TYPE ,
     1               NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2               NSEPP2 , NSEQP1 , KSTYPA , LSTYPA
C
      COMMON /DIMEN/  MBASIS ,  V2MAX  , V2MXP1 ,
     1               JMAX   , JMAXP1 , MDIM   , NFSYM0 , NFASY0 ,
     2               NFSYMJ , NFASYJ
C
      COMMON /LSFIT/  PARMAX , NUMPAR , ISOMAX , IVAR
C
      COMMON /SYS/    THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1                     THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2                     VELLGT , PLANCK , AVOGNO , PI , PREC ,
     4                     NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 ,
     5                     NFIL6 , NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6                     NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7                     NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6                     ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7                     IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8                     NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER ,
     9                       NATTS , PRTINT
C
      COMMON/BCOEFF/
     1      B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      COMMON/CRCOEF/
     1      CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
C
      COMMON/MORSE/RMK,AAS
      COMMON/MODIM/NOBAS,MBASP1,LENIW
C
      CONCOR=PLANCK*AVOGNO*1.0D+16/(1.6D+01*PI*PI*VELLGT)
      CONYZ=CONCOR
      CONXR=CONCOR
      CONCOR=-CONCOR
      SQ2=SQRT(2.0D+00)
      J=JP1-1
      REWIND NFIL11
      DO 5000 III=1,KONESY
      IOFFSY=(III-1)*NONESY
5000  READ (NFIL11) (VALSYM(IOFFSY+L), L=1,NONESY)
      KBDSYM=0
      IF (.NOT. SYMM) THEN
      REWIND NFIL12
      DO 5010 III=1,KONEAS
      IOFFAS=(III-1)*NONEAS
5010  READ (NFIL12) (VALASY(IOFFAS+L), L=1,NONEAS)
      KBDASY=0
      ENDIF
C
      DO 780 K1P1=1,JP1
      DO 770 KDEL=-1,1,2
      K2P1=K1P1+KDEL
      IF (K2P1 .LT. 1 .OR. K2P1 .GT. JP1) GOTO 770
      IF (K1P1 .GT. K2P1) THEN
            XJK=SQRT(FLOAT(J*JP1-(K2P1-1)*K2P1))
      ELSE
            XJK=SQRT(FLOAT(J*JP1-(K1P1-1)*K1P1))
      ENDIF
      IF (K1P1 .EQ. 1 .OR. K2P1 .EQ. 1) XJK=SQ2*XJK
      XKK=FLOAT(K1P1+K2P1-2)
      XXR=1.0D+00
      IF (K1P1 .GT. K2P1) XXR=-XXR
C
      DO 760 INDEX1=1,V2MXP1
      DO 750 INDEX2=1,V2MXP1
C
      KBDSYM=KBDSYM+1
      IOFFSY=(KBDSYM-1)*NONESY
      IF (.NOT.SYMM) THEN
          KBDASY=KBDASY+1
          IOFFAS=(KBDASY-1)*NONEAS
      ENDIF
      IF (K1P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 750
      IF (K2P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 750
C
      KNDEX=0
C
      IF (MOD(K1P1,2) .NE. 0) THEN
            INDK1=(K1P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK1=INDK1-1
      ELSE
            INDK1=(K1P1-2)/2
      ENDIF
      IF (MOD(K2P1,2) .NE. 0) THEN
            INDK2=(K2P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK2=INDK2-1
      ELSE
            INDK2=(K2P1-2)/2
      ENDIF
      IROWOF=NOFSRO+INDK1*V2MXP1*NDIMRO+(INDEX1-1)*NDIMRO
      ICOLOF=NOFSCO+INDK2*V2MXP1*NDIMCO+(INDEX2-1)*NDIMCO
      JROWOF=NOFSRO+INDK2*V2MXP1*NDIMRO+(INDEX2-1)*NDIMRO
      JCOLOF=NOFSCO+INDK1*V2MXP1*NDIMCO+(INDEX1-1)*NDIMCO
C
      IF (MOD(K1P1,2) .EQ. IEO) GOTO 80
      GOTO 90
C
C  2A. TERMS CONTAINING Y1
C
80    KNDEX=KNDEX+1
      GXR = CONXR*VALSYM(IOFFSY+9)*XJK*XXR
      DO 820 JL=1,NDIMCO
      DO 820 IR=1,NDIMRO
820   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 3A. TERMS CONTAINING Y3
C
      KNDEX=KNDEX+1
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(IOFFAS+8)*XJK*XXR
      ENDIF
      DO 840 JL=1,NDIMCO
      DO 840 IR=1,NDIMRO
840   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  4A. TERMS CONTAINING Y1*Y1
C
      KNDEX=KNDEX+1
      GXR = CONXR*VALSYM(IOFFSY+10)*XJK*XXR
      DO 860 JL=1,NDIMCO
      DO 860 IR=1,NDIMRO
860   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 5A. TERMS CONTAINING Y3*Y3
C
      KNDEX=KNDEX+1
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(IOFFAS+9)*XJK*XXR
      ENDIF
      DO 880 JL=1,NDIMCO
      DO 880 IR=1,NDIMRO
880   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 6A. TERMS CONTAINING Y1*Y3
C
      KNDEX=KNDEX+1
      GXR = CONXR*VALSYM(IOFFSY+11)*XJK*XXR
      DO 900 JL=1,NDIMCO
      DO 900 IR=1,NDIMRO
900   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  7A. TERMS CONTAINING Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      GXR=CONXR*VALSYM(IOFFSY+12)*XJK*XXR
      DO 920 JL=1,NDIMCO
      DO 920 IR=1,NDIMRO
920   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 8A. TERMS CONTAINING Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(IOFFAS+10)*XJK*XXR
      ENDIF
      DO 940 JL=1,NDIMCO
      DO 940 IR=1,NDIMRO
940   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  9A. TERMS CONTAINING Y1*Y1*Y3
C
      KNDEX=KNDEX+1
      GXR = CONXR*VALSYM(IOFFSY+13)*XJK*XXR
      DO 960 JL=1,NDIMCO
      DO 960 IR=1,NDIMRO
960   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 10A. TERMS CONTAINING Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(IOFFAS+11)*XJK*XXR
      ENDIF
      DO 980 JL=1,NDIMCO
      DO 980 IR=1,NDIMRO
980   HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  11A. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      GXR = CONXR*VALSYM(IOFFSY+14)*XJK*XXR
      DO 1000 JL=1,NDIMCO
      DO 1000 IR=1,NDIMRO
1000  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 12A. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(IOFFAS+12)*XJK*XXR
      ENDIF
      DO 1020 JL=1,NDIMCO
      DO 1020 IR=1,NDIMRO
1020  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  13A. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      KNDEX=KNDEX+1
      GXR = CONXR*VALSYM(IOFFSY+15)*XJK*XXR
      DO 1040 JL=1,NDIMCO
      DO 1040 IR=1,NDIMRO
1040  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 14A. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                     GXR = CONXR*VALASY(IOFFAS+13)*XJK*XXR
      ENDIF
      DO 1060 JL=1,NDIMCO
      DO 1060 IR=1,NDIMRO
1060  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 15A. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      GXR = CONXR*VALSYM(IOFFSY+16)*XJK*XXR
      DO 1080 JL=1,NDIMCO
      DO 1080 IR=1,NDIMRO
1080  HMAT(JROWOF+IR,JCOLOF+JL)=HMAT(JROWOF+IR,JCOLOF+JL)
     1                       +GXR*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
      GOTO 750
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C     (THIS TERM ONLY EXISTS FOR UNSYMMETRICAL MOLECULES).
C
90    CONTINUE
      IF (.NOT. SYMM) THEN
      G=CONYZ*VALASY(IOFFAS+1)*XJK*XKK
      DO 100 IR=1,NDIMRO
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G
      ENDIF
C
C  2. TERMS CONTAINING Y1
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 1)*XJK*XKK
      GXR = CONXR*VALSYM(IOFFSY+9)*XJK*XXR
      DO 120 JL=1,NDIMCO
      DO 120 IR=1,NDIMRO
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 3. TERMS CONTAINING Y3
C
      KNDEX=KNDEX+1
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                       G = CONYZ*VALASY(IOFFAS+ 2)*XJK*XKK
                     GXR = CONXR*VALASY(IOFFAS+8)*XJK*XXR
      ENDIF
      DO 140 JL=1,NDIMCO
      DO 140 IR=1,NDIMRO
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  4. TERMS CONTAINING Y1*Y1
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 2)*XJK*XKK
      GXR = CONXR*VALSYM(IOFFSY+10)*XJK*XXR
      DO 160 JL=1,NDIMCO
      DO 160 IR=1,NDIMRO
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 5. TERMS CONTAINING Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                       G = CONYZ*VALASY(IOFFAS+ 3)*XJK*XKK
                     GXR = CONXR*VALASY(IOFFAS+9)*XJK*XXR
      ENDIF
      DO 180 JL=1,NDIMCO
      DO 180 IR=1,NDIMRO
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 6. TERMS CONTAINING Y1*Y3
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 3)*XJK*XKK
      GXR = CONXR*VALSYM(IOFFSY+11)*XJK*XXR
      DO 200 JL=1,NDIMCO
      DO 200 IR=1,NDIMRO
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 4)*XJK*XKK
      GXR=CONXR*VALSYM(IOFFSY+12)*XJK*XXR
      DO 220 JL=1,NDIMCO
      DO 220 IR=1,NDIMRO
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                      G = CONYZ*VALASY(IOFFAS+ 4)*XJK*XKK
                     GXR = CONXR*VALASY(IOFFAS+10)*XJK*XXR
      ENDIF
      DO 240 JL=1,NDIMCO
      DO 240 IR=1,NDIMRO
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 5)*XJK*XKK
      GXR = CONXR*VALSYM(IOFFSY+13)*XJK*XXR
      DO 260 JL=1,NDIMCO
      DO 260 IR=1,NDIMRO
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                        G = CONYZ*VALASY(IOFFAS+ 5)*XJK*XKK
                     GXR = CONXR*VALASY(IOFFAS+11)*XJK*XXR
      ENDIF
      DO 280 JL=1,NDIMCO
      DO 280 IR=1,NDIMRO
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 6)*XJK*XKK
      GXR = CONXR*VALSYM(IOFFSY+14)*XJK*XXR
      DO 300 JL=1,NDIMCO
      DO 300 IR=1,NDIMRO
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                        G = CONYZ*VALASY(IOFFAS+ 6)*XJK*XKK
                     GXR = CONXR*VALASY(IOFFAS+12)*XJK*XXR
      ENDIF
      DO 320 JL=1,NDIMCO
      DO 320 IR=1,NDIMRO
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 7)*XJK*XKK
      GXR = CONXR*VALSYM(IOFFSY+15)*XJK*XXR
      DO 340 JL=1,NDIMCO
      DO 340 IR=1,NDIMRO
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G=-G
      GXR=-GXR
      IF (.NOT. SYMM) THEN
                       G = CONYZ*VALASY(IOFFAS+ 7)*XJK*XKK
                     GXR = CONXR*VALASY(IOFFAS+13)*XJK*XXR
      ENDIF
      DO 360 JL=1,NDIMCO
      DO 360 IR=1,NDIMRO
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      KNDEX=KNDEX+1
       G = CONYZ*VALSYM(IOFFSY+ 8)*XJK*XKK
      GXR = CONXR*VALSYM(IOFFSY+16)*XJK*XXR
      DO 380 JL=1,NDIMCO
      DO 380 IR=1,NDIMRO
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +(G+GXR)*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 16. TERMS CONTAINING Y1*P1+P1*Y1
C
      KNDEX=KNDEX+1
      G = CONCOR*XJK*XXR*VALSYM(IOFFSY+17)
      DO 400 JL=1,NDIMCO
      DO 400 IR=1,NDIMRO
400   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 17. TERMS CONTAINING Y3*P3+P3*Y3
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(IOFFAS+15)
      DO 420 JL=1,NDIMCO
      DO 420 IR=1,NDIMRO
420   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 18. TERMS CONTAINING Y3*P1
C
      KNDEX=KNDEX+1
      G = 2.0D+00*CONCOR*XJK*XXR*VALSYM(IOFFSY+18)
      DO 440 JL=1,NDIMCO
      DO 440 IR=1,NDIMRO
440   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 19. TERMS CONTAINING Y1*P3
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*XJK*XXR*VALASY(IOFFAS+14)
      DO 460 JL=1,NDIMCO
      DO 460 IR=1,NDIMRO
460   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 20. TERMS CONTAINING Y1*Y1*P1+P1*Y1*Y1
C
      KNDEX=KNDEX+1
      G = CONCOR*XJK*XXR*VALSYM(IOFFSY+19)
      DO 480 JL=1,NDIMCO
      DO 480 IR=1,NDIMRO
480   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 21. TERMS CONTAINING Y3*Y3*P3+P3*Y3*Y3
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(IOFFAS+17)
      DO 500 JL=1,NDIMCO
      DO 500 IR=1,NDIMRO
500   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 22. TERMS CONTAINING P1*Y3*Y3
C
      KNDEX=KNDEX+1
      G = 2.0D+00*CONCOR*XJK*XXR*VALSYM(IOFFSY+20)
      DO 520 JL=1,NDIMCO
      DO 520 IR=1,NDIMRO
520   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 23. TERMS CONTAINING P3*Y1*Y1
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*XJK*XXR*VALASY(IOFFAS+16)
      DO 540 JL=1,NDIMCO
      DO 540 IR=1,NDIMRO
540   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 24. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3
C
      KNDEX=KNDEX+1
      G = CONCOR*XJK*XXR*VALSYM(IOFFSY+21)
      DO 560 JL=1,NDIMCO
      DO 560 IR=1,NDIMRO
560   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 25. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(IOFFAS+18)
      DO 580 JL=1,NDIMCO
      DO 580 IR=1,NDIMRO
580   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 26. TERMS CONTAINING Y1*Y1*Y1*P1+P1*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      G = CONCOR*XJK*XXR*VALSYM(IOFFSY+22)
      DO 600 JL=1,NDIMCO
      DO 600 IR=1,NDIMRO
600   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 27. TERMS CONTAINING Y3*Y3*Y3*P3+P3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(IOFFAS+20)
      DO 620 JL=1,NDIMCO
      DO 620 IR=1,NDIMRO
620   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 28. TERMS CONTAINING P1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      G = 2.0D+00*CONCOR*XJK*XXR*VALSYM(IOFFSY+23)
      DO 640 JL=1,NDIMCO
      DO 640 IR=1,NDIMRO
640   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 29. TERMS CONTAINING P3*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = 2.0D+00*CONCOR*XJK*XXR*VALASY(IOFFAS+19)
      DO 660 JL=1,NDIMCO
      DO 660 IR=1,NDIMRO
660   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 30. TERMS CONTAINING (Y1*Y1*P1+P1*Y1*Y1)*Y3
C
      KNDEX=KNDEX+1
      G = CONCOR*XJK*XXR*VALSYM(IOFFSY+24)
      DO 680 JL=1,NDIMCO
      DO 680 IR=1,NDIMRO
680   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 31. TERMS CONTAINING (Y3*Y3*P3+P3*Y3*Y3)*Y1
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(IOFFAS+22)
      DO 700 JL=1,NDIMCO
      DO 700 IR=1,NDIMRO
700   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 32. TERMS CONTAINING (Y1*P1+P1*Y1)*Y3*Y3
C
      KNDEX=KNDEX+1
      G = CONCOR*XJK*XXR*VALSYM(IOFFSY+25)
      DO 720 JL=1,NDIMCO
      DO 720 IR=1,NDIMRO
720   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 33. TERMS CONTAINING (Y3*P3+P3*Y3)*Y1*Y1
C
      KNDEX=KNDEX+1
      G = -G
      IF (.NOT. SYMM) G = CONCOR*XJK*XXR*VALASY(IOFFAS+21)
      DO 740 JL=1,NDIMCO
      DO 740 IR=1,NDIMRO
740   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
750   CONTINUE
760   CONTINUE
770   CONTINUE
780   CONTINUE
      RETURN
      END
C
C
      SUBROUTINE DELK2 ( VALSYM , VALASY , SMAT   , HMAT   ,
     1                   NOFSRO , NOFSCO , NDIMRO , NDIMCO ,
     1                   JP1    , IRODIM , IEO    , ITAU   ,
     1                   INTSYM , INTASY , ISTOFF , JSTOFF ,
     4                   NOPERS       )
      IMPLICIT REAL*8 (A-H,O-Z)
C
      REAL*8 M1,M2,M3,M,U1,U3,U13,V,RHO,EPS,
     1      CR,SR,CSE,SNE,
     2      CRE,SRE,CORO,EPSP,EPSPP,EPSPPP
C
      REAL*8 AMASS(3,10)
C
      REAL*8 RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1       AA1,AA3,
     2       F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3       F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4       F13,F1A13,F2A13,F3A13,
     5       F111,F1A111,F2A111,F333,F1A333,F2A333,
     6       F113,F1A113,F2A113,F133,F1A133,F2A133,
     7       F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8       F1333,FA1333,F1133,FA1133,
     8       RE12 , RE32 , RHOREF , VMIN
C
      REAL*8 ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1      PREC
C
      REAL*8 THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1      THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2      VELLGT , PLANCK , AVOGNO , DEGRAD , RADDEG ,
     3      PI
C
      REAL*8   B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      REAL*8   CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
      INTEGER NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 , NFIL6 ,
     5       NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6       NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7       NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6       ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7       IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8       NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER,
     9       ISOMAX , NATTS  , V0TYPE , IVAR(55) , PARMAX ,
     1       NUMPAR , PRTINT
C
      INTEGER V1 ,V2, V3 , V2MXP1, V2P1,
     1       NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2       NSEPP2 , NSEQP1 , MBASIS ,
     3       MDIM , NFSYM0, NFASY0, NFSYMJ, NFASYJ,
     4       KSTYPA(2) , LSTYPA(2) , JMAX , V2MAX , JMAXP1
C
      INTEGER IQUANT(5,10)
C
      LOGICAL SYMM
C
      REAL*8 RMK(2),AAS(2)
      INTEGER NOBAS,MBASP1,LENIW
      INTEGER LENINT,IOSC1,IOSC3,I,J,IR,JL
      REAL*8 G,GC1,GC3,GC1113,GC3133,GC1133,GC3113
      REAL*8 SMAT(NOBAS,NOBAS,NOPERS),VALSYM(INTSYM),VALASY(INTASY),
     1       HMAT(IRODIM,IRODIM)
      REAL*8  CONCOR,CONFC1,CONG11,CONG33,CONG13,CORHOE
      COMMON /ISOTOP/ IQUANT,AMASS
C
      COMMON /BOOKK/ NZERSY , NZERAS , NONESY , NONEAS , NTWOSY ,
     1               NTWOAS , KZERSY , KZERAS , KONESY , KONEAS ,
     2               KTWOSY , KTWOAS
C
      COMMON /VALUES/ RHO,EPS,EPSP,EPSPP,EPSPPP,
     1               CR,SR,CSE,SNE,CRE,SRE,CORO
C
      COMMON /MOLCUL/ RHOE,FA1,FA2,FA3,FA4,FA5,FA6,FA7,FA8,
     1               AA1,AA3,
     2               F1A1,F2A1,F3A1,F4A1,F1A3,F2A3,F3A3,F4A3,
     3               F11,F1A11,F2A11,F3A11,F33,F1A33,F2A33,F3A33,
     4               F13,F1A13,F2A13,F3A13,
     5               F111,F1A111,F2A111,F333,F1A333,F2A333,
     6               F113,F1A113,F2A113,F133,F1A133,F2A133,
     7               F1111,FA1111,F3333,FA3333,F1113,FA1113,
     8               F1333,FA1333,F1133,FA1133,
     8               RE12 , RE32 , M1 , M2 , M3 , M ,
     9               U1 , U3 , U13 , V ,
     1               SYMM
C
      COMMON /INTEG/  ETRIAL , RHOMAX , PNM1 , HBASE , HSTEP , EGUESS ,
     1               RHOREF , VMIN , V0TYPE ,
     1               NSTINT , NSERIN , NSERP , NSERQ , KQUA , NTEST ,
     2               NSEPP2 , NSEQP1 , KSTYPA , LSTYPA
C
      COMMON /DIMEN/  MBASIS ,  V2MAX  , V2MXP1 ,
     1               JMAX   , JMAXP1 , MDIM   , NFSYM0 , NFASY0 ,
     2               NFSYMJ , NFASYJ
C
      COMMON /LSFIT/  PARMAX , NUMPAR , ISOMAX , IVAR
C
      COMMON /SYS/    THRSH1 , THRSH2 , THRSH3 , THRSH4 , THRSH5 ,
     1                     THRSH6 , THRSH7 , THRSH8 , THRSH9 , THRSHX ,
     2                     VELLGT , PLANCK , AVOGNO , PI , PREC ,
     4                     NFIL1 , NFIL2 , NFIL3 , NFIL4 , NFIL5 ,
     5                     NFIL6 , NFIL7 , NFIL8 , NFIL9 , NFIL10 ,
     6                     NFIL11 , NFIL12 , NFIL13 , NFIL14 , NFIL15 ,
     7                     NFIL16 , NFIL17 , NFIL18 , NFIL19 , NFIL20 ,
     6                     ITEST  , IPRINT , NSTNR , NSTNIN , IREST ,
     7                     IISOT , IQUAS , ISYMS , NISOT , NQUAS ,
     8                     NUMQUA , NOPTIT , NOPTIM , IOBSER , NOBSER ,
     9                       NATTS , PRTINT
C
      COMMON/BCOEFF/
     1      B11,B13,B111,B133,B113,
     2      B1111,B1333,B1113,B1133,
     3      B11111,B13333,B11113,B11333,B11133,
     4      B31,B33,B311,B333,B313,
     5      B3111,B3333,B3113,B3133,
     6      B31111,B33333,B31113,B31333,B31133
C
      COMMON/CRCOEF/
     1      CR1,CR3,CR11,CR33,CR13,
     2      CR111,CR333,CR113,CR133,
     3      CR1111,CR3333,CR1113,CR1333,CR1133
C
C
      COMMON/MORSE/RMK,AAS
      COMMON/MODIM/NOBAS,MBASP1,LENIW
C
      CONXX=-PLANCK*AVOGNO*1.0D+16/(3.2D+01*PI*PI*VELLGT)
      SQ2=SQRT(2.0D+00)
      J=JP1-1
      REWIND NFIL13
      DO 5000 III=1,KTWOSY
      IOFFSY=(III-1)*NTWOSY
5000  READ (NFIL13) (VALSYM(IOFFSY+L), L=1,NTWOSY)
      KBDSYM=0
      IF (.NOT. SYMM) THEN
      REWIND NFIL14
      DO 5010 III=1,KTWOAS
      IOFFAS=(III-1)*NTWOAS
5010  READ (NFIL14) (VALASY(IOFFAS+L), L=1,NTWOAS)
      KBDASY=0
      ENDIF
C
      DO 460 K1P1=1,JP1
      DO 440 KDEL=-2,2,4
      K2P1=K1P1+KDEL
      IF (K2P1 .LT. 1 .OR. K2P1 .GT. JP1) GOTO 440
      IF (K1P1 .GT. K2P1) THEN
            XJK=SQRT(FLOAT((J*JP1-(K2P1-1)*K2P1)*(J*JP1-K2P1*(K2P1+1))))
      ELSE
            XJK=SQRT(FLOAT((J*JP1-(K1P1-1)*K1P1)*(J*JP1-K1P1*(K1P1+1))))
      ENDIF
C
      IF (K1P1 .EQ. 1 .OR. K2P1 .EQ. 1) XJK=SQ2*XJK
      DO 420 INDEX1=1,V2MXP1
      DO 400 INDEX2=1,V2MXP1
C
      KBDSYM=KBDSYM+1
      IOFFSY=(KBDSYM-1)*NTWOSY
      IF (.NOT.SYMM) THEN
          KBDASY=KBDASY+1
          IOFFAS=(KBDASY-1)*NTWOAS
      ENDIF
      IF (MOD(K1P1,2) .EQ. IEO) GOTO 400
      IF (K1P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 400
      IF (K2P1 .EQ. 1 .AND. MOD(J+ITAU,2) .NE. 0) GOTO 400
C
      KNDEX=0
C
      IF (MOD(K1P1,2) .NE. 0) THEN
            INDK1=(K1P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK1=INDK1-1
      ELSE
            INDK1=(K1P1-2)/2
      ENDIF
      IF (MOD(K2P1,2) .NE. 0) THEN
            INDK2=(K2P1-1)/2
            IF (MOD(J+ITAU,2) .NE. 0) INDK2=INDK2-1
      ELSE
            INDK2=(K2P1-2)/2
      ENDIF
      IROWOF=NOFSRO+INDK1*V2MXP1*NDIMRO+(INDEX1-1)*NDIMRO
      ICOLOF=NOFSCO+INDK2*V2MXP1*NDIMCO+(INDEX2-1)*NDIMCO
C
C  1. LEADING TERM (NOT DEPENDING ON STRETCHING COORDINATES)
C
      G =  CONXX*(VALSYM(IOFFSY+ 1)-VALSYM(IOFFSY+10))*XJK
      DO 100 IR=1,NDIMRO
100   HMAT(IROWOF+IR,ICOLOF+IR)=HMAT(IROWOF+IR,ICOLOF+IR)
     1                       +G
C
C  2. TERMS CONTAINING Y1
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 2)-VALSYM(IOFFSY+11))*XJK
      DO 120 JL=1,NDIMCO
      DO 120 IR=1,NDIMRO
120   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 3. TERMS CONTAINING Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM)
     2                 G = CONXX*(VALASY(IOFFAS+ 1)
     2                           -VALASY(IOFFAS+ 7))*XJK
      DO 140 JL=1,NDIMCO
      DO 140 IR=1,NDIMRO
140   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  4. TERMS CONTAINING Y1*Y1
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 3)-VALSYM(IOFFSY+12))*XJK
      DO 160 JL=1,NDIMCO
      DO 160 IR=1,NDIMRO
160   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 5. TERMS CONTAINING Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM)
     2       G = CONXX*(VALASY(IOFFAS+ 2)-VALASY(IOFFAS+ 8))*XJK
      DO 180 JL=1,NDIMCO
      DO 180 IR=1,NDIMRO
180   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 6. TERMS CONTAINING Y1*Y3
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 4)-VALSYM(IOFFSY+13))*XJK
      DO 200 JL=1,NDIMCO
      DO 200 IR=1,NDIMRO
200   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  7. TERMS CONTAINING Y1*Y1*Y1
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 5)-VALSYM(IOFFSY+14))*XJK
      DO 220 JL=1,NDIMCO
      DO 220 IR=1,NDIMRO
220   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 8. TERMS CONTAINING Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM)
     2      G = CONXX*(VALASY(IOFFAS+ 3)-VALASY(IOFFAS+ 9))*XJK
      DO 240 JL=1,NDIMCO
      DO 240 IR=1,NDIMRO
240   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  9. TERMS CONTAINING Y1*Y1*Y3
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 6)-VALSYM(IOFFSY+15))*XJK
      DO 260 JL=1,NDIMCO
      DO 260 IR=1,NDIMRO
260   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 10. TERMS CONTAINING Y1*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM)
     2      G = CONXX*(VALASY(IOFFAS+ 4)-VALASY(IOFFAS+10))*XJK
      DO 280 JL=1,NDIMCO
      DO 280 IR=1,NDIMRO
280   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  11. TERMS CONTAINING Y1*Y1*Y1*Y1
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 7)-VALSYM(IOFFSY+16))*XJK
      DO 300 JL=1,NDIMCO
      DO 300 IR=1,NDIMRO
300   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 12. TERMS CONTAINING Y3*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM)
     2    G = CONXX*(VALASY(IOFFAS+ 5)-VALASY(IOFFAS+11))*XJK
      DO 320 JL=1,NDIMCO
      DO 320 IR=1,NDIMRO
320   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C  13. TERMS CONTAINING Y1*Y1*Y1*Y3
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 8)-VALSYM(IOFFSY+17))*XJK
      DO 340 JL=1,NDIMCO
      DO 340 IR=1,NDIMRO
340   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 14. TERMS CONTAINING Y1*Y3*Y3*Y3
C
      KNDEX=KNDEX+1
      IF (.NOT. SYMM)
     2       G = CONXX*(VALASY(IOFFAS+ 6)-VALASY(IOFFAS+12))*XJK
      DO 360 JL=1,NDIMCO
      DO 360 IR=1,NDIMRO
360   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
C
C 15. TERMS CONTAINING Y1*Y1*Y3*Y3
C
      KNDEX=KNDEX+1
       G = CONXX*(VALSYM(IOFFSY+ 9)-VALSYM(IOFFSY+18))*XJK
      DO 380 JL=1,NDIMCO
      DO 380 IR=1,NDIMRO
380   HMAT(IROWOF+IR,ICOLOF+JL)=HMAT(IROWOF+IR,ICOLOF+JL)
     1                       +G*SMAT(ISTOFF+IR,JSTOFF+JL,KNDEX)
400   CONTINUE
420   CONTINUE
440   CONTINUE
460   CONTINUE
      RETURN
      END
